#ifndef MY_MACRO_H
#define MY_MACRO_H

enum DataFlow
{
    DATA_FLOW_NONE,
    PACKET_TO_FRAME,
    FRAME_TO_PACKET,
    PACKET_TO_PACKET,
    FRAME_TO_FRAME
};

#define DEFAULT_QUEUE_MAX_SIZE 64
#define DEFAULT_PACKET_QUEUE_MAX_SIZE 64
#define DEFAULT_FRAME_QUEUE_MAX_SIZE 64

#define DEFAULT_THREAD_TIMEOUT_MICROSECOND 5
#define THREAD_NO_TIMEOUT -1

#define EXTERNAL_PLAY_STREAM_INDEX 0x10000
#define AUDIO_PLAY_STREAM_INDEX 0x10000 - 1
#define VIDEO_PLAY_STREAM_INDEX 0x10000 - 2
#define SUBTITLE_PLAY_STREAM_INDEX 0x10000 - 3

#define NAN __builtin_nanf("0x7fc00000")

#endif // MY_MACRO_H
